# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d00e249555c8d1f7013f53d775f53578419a9944558f4e88a8cd96cf8d7a18702319541570498e0404b3532bfe4f7270cefddb48dba1e37cf94eb4fadbb4518a

test:
  secret_key_base: 503498475ac73eccd35073db3e7c00a55b988f53756d670b722381235f08d9c1889645053b5663ab68dee9e3752be269bd576e3b4613aa18e24d5236c3b1b58b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
